### ISSUE TITLE
Implementation TODO

### ISSUE THREAD

**Issue by Lulalaby** [Aiko-IT-Systems/Discord-React-Components#46]
## Missing Components

- [ ] Select Menus
- [ ] Context Menu Commands (User/Message)
- [ ] Automod Messages
- [ ] Media Channel Mentions
- [ ] Locked Channels Mentions
- [ ] Linked Role Tags
- [ ] Modals

## Missing / Broken Functionality

- [ ] Copy functions (ids, links, etc.)
- [ ] Button Interactions
- [ ] Audio Files
